language: node_js
node_js:
  - "14"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm prune
  - npm install -g @angular/cli
  - npm install

script:
  - npm run lint
  - npm run build
